FROM node:12.4.0-alpine as debug

WORKDIR /usr/src/app

COPY ./src/package.json /usr/app/package.json
RUN npm install
RUN npm install -g nodemon

COPY ./src/ /usr/src/app

ENTRYPOINT [ "nodemon","--inspect=0.0.0.0","./src/index.js" ]

FROM node:12.4.0-alpine as prod

WORKDIR /usr/src/app
COPY ./src/package.json /usr/src/app/package.json
RUN npm install
COPY ./src/ /usr/src/app/

CMD node .